# config.yaml

EMAIL_USERNAME: "seumkt@gmail.com"
EMAIL_PASSWORD: "lhksxmysnfptxknf"

PG_DBNAME: "engclinic_db"
PG_USER: "postgres"
PG_PASSWORD: "pgadmin"
PG_HOST: "127.0.0.1"
PG_PORT: "5432"