"""empty message

Revision ID: 1370be43ea13
Revises: 6d9b70ac3f47
Create Date: 2023-11-01 23:47:05.635132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1370be43ea13'
down_revision = '6d9b70ac3f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_medida_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'material', ['unidade_medida_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unidade_medida_id')

    # ### end Alembic commands ###
