"""empty message

Revision ID: 303bca86f229
Revises: 95e448e5351b
Create Date: 2023-11-06 12:47:11.221301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303bca86f229'
down_revision = '95e448e5351b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setor',
    sa.Column('id_setor', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=True),
    sa.Column('setor', sa.String(length=255), nullable=True),
    sa.Column('chefe', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_setor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setor')
    # ### end Alembic commands ###
