"""empty message

Revision ID: 3d62a9b9e7e2
Revises: 
Create Date: 2024-01-23 20:21:59.682274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d62a9b9e7e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadfornecedor',
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('CNPJ', sa.String(length=130), nullable=False),
    sa.Column('Razao_Social', sa.String(length=100), nullable=False),
    sa.Column('Nome_Fantasia', sa.String(length=100), nullable=False),
    sa.Column('Endereco', sa.String(length=100), nullable=False),
    sa.Column('Numero', sa.String(length=10), nullable=False),
    sa.Column('Complemento', sa.String(length=50), nullable=True),
    sa.Column('Bairro', sa.String(length=50), nullable=False),
    sa.Column('CEP', sa.String(length=9), nullable=False),
    sa.Column('Cidade', sa.String(length=50), nullable=False),
    sa.Column('UF', sa.String(length=2), nullable=False),
    sa.Column('Pais', sa.String(length=50), nullable=False),
    sa.Column('Telefone', sa.String(length=15), nullable=False),
    sa.Column('Ramal', sa.String(length=10), nullable=True),
    sa.Column('Celular', sa.String(length=15), nullable=False),
    sa.Column('Contato', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Site', sa.String(), nullable=True),
    sa.Column('Fabricante', sa.Boolean(), nullable=True),
    sa.Column('Fornecedor', sa.Boolean(), nullable=True),
    sa.Column('Observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_fornecedor'),
    sa.UniqueConstraint('id_fornecedor')
    )
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=True),
    sa.Column('razao_social', sa.String(length=100), nullable=True),
    sa.Column('nome_pessoa_fisica', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('ramal', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('diretor', sa.String(length=100), nullable=True),
    sa.Column('telefone_diretor', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_cliente')
    )
    op.create_table('tipo_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_os', sa.String(length=255), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_expiration', sa.DateTime(), nullable=True),
    sa.Column('current_password', sa.String(length=500), nullable=True),
    sa.Column('new_password', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_reset_token'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agendamento',
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('data_agendamento', sa.Date(), nullable=False),
    sa.Column('data_lancamento', sa.DateTime(), nullable=False),
    sa.Column('tipo_servico', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_agendamento')
    )
    op.create_table('centro_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setor',
    sa.Column('id_setor', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=True),
    sa.Column('setor', sa.String(length=255), nullable=True),
    sa.Column('chefe', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_setor')
    )
    op.create_table('ordem_servico',
    sa.Column('id_os', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo_os_id', sa.Integer(), nullable=False),
    sa.Column('motivo_os', sa.Text(), nullable=False),
    sa.Column('localizacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id_setor'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['tipo_os_id'], ['tipo_os.id'], ),
    sa.PrimaryKeyConstraint('id_os')
    )
    op.create_table('material',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('tipo_material', sa.String(length=20), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id_os'], ),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_table('entrada_acessorios',
    sa.Column('id_acessorio', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('fabricante_id', sa.Integer(), nullable=False),
    sa.Column('item_material', sa.String(length=255), nullable=True),
    sa.Column('rm', sa.String(length=255), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('aquisicao', sa.String(length=50), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('localizacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['fabricante_id'], ['cadfornecedor.id_fornecedor'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id_material'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id_setor'], ),
    sa.PrimaryKeyConstraint('id_acessorio')
    )
    op.create_table('item_material',
    sa.Column('id_itmaterial', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('fabricante_id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('foto_material', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('tipo_material_id', sa.Integer(), nullable=False),
    sa.Column('unidade_medida_id', sa.Integer(), nullable=False),
    sa.Column('data_consumo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fabricante_id'], ['cadfornecedor.id_fornecedor'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id_material'], ),
    sa.ForeignKeyConstraint(['tipo_material_id'], ['material.id_material'], ),
    sa.ForeignKeyConstraint(['unidade_medida_id'], ['material.id_material'], ),
    sa.PrimaryKeyConstraint('id_itmaterial')
    )
    op.create_table('ordem_servico_material',
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id_material'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id_os'], ),
    sa.PrimaryKeyConstraint('ordem_servico_id', 'material_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordem_servico_material')
    op.drop_table('item_material')
    op.drop_table('entrada_acessorios')
    op.drop_table('material')
    op.drop_table('ordem_servico')
    op.drop_table('setor')
    op.drop_table('centro_custo')
    op.drop_table('agendamento')
    op.drop_table('users')
    op.drop_table('tipo_os')
    op.drop_table('cliente')
    op.drop_table('cadfornecedor')
    # ### end Alembic commands ###
