"""empty message

Revision ID: 567c01f835a8
Revises: 3d62a9b9e7e2
Create Date: 2024-01-23 20:29:51.778780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567c01f835a8'
down_revision = '3d62a9b9e7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadfornecedor', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_fornecedor'])

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_cliente'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('cadfornecedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
