"""empty message

Revision ID: 59904c4a8892
Revises: 8e5de37594cb
Create Date: 2023-11-02 14:06:25.171968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59904c4a8892'
down_revision = '8e5de37594cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=True),
    sa.Column('razao_social', sa.String(length=100), nullable=True),
    sa.Column('nome_pessoa_fisica', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('ramal', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('diretor', sa.String(length=100), nullable=True),
    sa.Column('telefone_diretor', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_cliente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente')
    # ### end Alembic commands ###
