"""empty message

Revision ID: 59bd1d0e311f
Revises: 1370be43ea13
Create Date: 2023-11-02 11:18:49.775596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bd1d0e311f'
down_revision = '1370be43ea13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_consumo', sa.DateTime(), nullable=True))

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('data_criacao')

    with op.batch_alter_table('item_material', schema=None) as batch_op:
        batch_op.drop_column('data_consumo')

    # ### end Alembic commands ###
