"""empty message

Revision ID: c8ad2b828f87
Revises: a44cc587dea6
Create Date: 2023-11-03 10:19:47.062067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ad2b828f87'
down_revision = 'a44cc587dea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_os', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_os', schema=None) as batch_op:
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
