"""empty message

Revision ID: c8dce7a78c48
Revises: 6daac1f6475b
Create Date: 2023-11-08 16:23:24.341543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8dce7a78c48'
down_revision = '6daac1f6475b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
