"""empty message

Revision ID: dee2d421a1dc
Revises: 1cd7d5e69323
Create Date: 2023-11-01 17:31:22.339135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee2d421a1dc'
down_revision = '1cd7d5e69323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadfornecedor', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_fornecedor'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadfornecedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
